name: Docker Image CI

on:
  schedule:
    - cron: '0 */12 * * *'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, aarch64, armhf]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare
        id: prep
        run: |
          echo "platform=linux/${{ matrix.architecture }}" >> $GITHUB_ENV
          echo "tag=${{ matrix.architecture}}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "build-args=ARCH=${{ matrix.architecture }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.platform }}
          build-args: ${{ env.build-args }}
          push: true
          provenance: false
          tags: ${{ github.repository }}:${{ env.tag }}

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifests
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          IMAGE=${{ github.repository }}
          TAG=${GITHUB_SHA:0:7}
          docker manifest create ${IMAGE}:${TAG} ${IMAGE}:amd64-${TAG} ${IMAGE}:armhf-${TAG} ${IMAGE}:aarch64-${TAG}
          docker manifest push   ${IMAGE}:${GITHUB_SHA:0:7}
          docker manifest create ${IMAGE}:latest ${IMAGE}:amd64-${TAG} ${IMAGE}:armhf-${TAG} ${IMAGE}:aarch64-${TAG}
          docker manifest push   ${IMAGE}:latest
